name: CI - CD

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    tags:
      - 'v*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0
      - name: Set env
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Build and push
        uses: docker/build-push-action@v2
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: docker-registry.theme-spider.com/edu-vr-cms:${{ steps.vars.outputs.tag }}
  redeploy:
    name: Redeploy
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary
      - name: Adding Known Hosts
        run: ssh-keyscan -p ${{ secrets.SSH_PORT}} -H ${{ secrets.SSH_HOST }}  >> ~/.ssh/known_hosts
      - name: Set env
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Deploy
        uses: appleboy/ssh-action@master
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /root/projects
            chown $(whoami) .
            docker ps
            echo ${{ steps.vars.outputs.tag }}
            docker ps --filter name=edu-vr-cms:* --filter status=running -aq | xargs docker stop
            docker run -d -p 8088:3000 --restart always --name edu-vr-cms_${{ steps.vars.outputs.tag }} docker-registry.theme-spider.com/edu-vr-cms:${{ steps.vars.outputs.tag }}
            docker ps
